### PR TITLE
ProtonVPN menu mod

### PR DESCRIPTION
**Pull request by sirakav**
https://www.reddit.com/r/ProtonVPN/comments/9qxcap/ive_made_a_better_menu_for_protonvpn_linux_client/

### CODE REVIEW

**Comment by julemand101** [comment]
I think there are some changes in the README.md you should leave out of this pull request. E.g. you are changing the URL and the name of the project. :)

**Comment by sirakav** [comment]
You are right, didn't think about that before requesting.

**Comment by Rafficer** [comment]
IMO it would be better to replace this menu with the current `-c` menu and not create a different, new option :)

**Comment by sirakav** [comment]
Well, I did it this way because I wanted to leave all of the old functionality in place.
If I would replace it, it would be more like a update then an extension and even maybe some people like the old menu. 
I guess we need to wait for @mazen160  opinion.

**Comment by mazen160** [comment]
Hi @sirakav!

First of all, this design is really beautiful :fire: 
Everyone loves it.

I have tested it. It shows how the dialog implementation is sequenced and interactive. I believe it would be better to have all menus (since we can have everything without breaking functionality :) )

`$pvpn -m` seems like an actual GUI :100: 

Great work!!

**Pull request merged**
