### PR TITLE
Jm/cli fixups

### PR DESCRIPTION
**Pull request by jmarkowski**

### CODE REVIEW

**Comment by xilopaint** [comment]
There's no inconsistency on that user confirmation. Your branch have conflicts with master branch. This is the actual code:

https://github.com/ProtonVPN/protonvpn-cli/blob/86f6718d7e4209148dda7337a0c98478768e49d0/protonvpn-cli.sh#L66-L75

**Comment by jmarkowski** [comment]
I've rebased the work to the latest work in 'master'. There is an inconsistency that has been fixed.

**Comment by xilopaint** [comment]
There's no inconsistency. The uppercase letter identifies the default option if the users hits enter.

https://askubuntu.com/questions/322600/do-you-want-to-continuey-n-why-the-upper-case

**Comment by jmarkowski** [comment]
Understood!

**Pull request merged**
