### PR TITLE
Improve randomness of --random-connect for the free tier

### PR DESCRIPTION
**Pull request by xilopaint**

### CODE REVIEW

**Comment by mazen160** [comment]
Hi @xilopaint 

I have checked the PR. It should not work and should trigger an exception. using `random` is a single time is sufficient for the task :)
I don't think we should add additional round for randomizing, as random.choice does the task as needed. However, There might be an addition on the future to do extra checks by not choosing the previous VPN.

 

The reason that it should not work that the first random.choice chooses a single element from the list. The second random.choice input is isn't a list, which triggers an exception.

Thanks
Mazin

**Comment by xilopaint** [comment]
Really? It works perfectly for me:

```
$ sudo pvpn -r
Fetching ProtonVPN Servers...
Connecting...
[$] Connected!
[#] New IP: 209.58.142.157
```

What exception is thrown for you?

Btw, the same method with double `random.choice` was merged in a previous PR from me (#54).

The second `random.choice` should improve the randomness for the free tier, since this tier, unlike the paid ones, have several servers for each ID. You can check the JSON response to confirm this.

Your algorithm select always the first server of the ID. Look your code:

`print(random.choice(output)["Servers"][0]["ID"])`

Otherwise, my code does a `random.choice` to select the candidate and another one to select the server:

`print(random.choice(random.choice(output)["Servers"])["ID"])`

**Comment by xilopaint** [comment]
@mazen160 Look at a typical free tier candidate. It has 23 servers. Your code choses always the first server. My code is random.

```
{
  u'Location': {
    u'Lat': 38.7701,
    u'Long': -77.6321
  },
  u'Status': 1,
  u'Domain': u'us-free-01.protonvpn.com',
  u'Load': 59,
  u'Features': 0,
  u'Servers': [
    {
      u'EntryIP': u'108.59.0.37',
      u'Status': 1,
      u'Domain': u'us-va-101.protonvpn.com',
      u'ExitIP': u'108.59.0.37',
      u'ID': u'Uc0Z4tdf4clwVr4eDSPY0bWjH9kIzvLeQ-qudaHD-WJKY21IfFV2t73civ-hnJN7dtbGpV5eUfX5DOKE_nWWcQ=='
    },
    {
      u'EntryIP': u'108.59.0.38',
      u'Status': 1,
      u'Domain': u'us-va-102.protonvpn.com',
      u'ExitIP': u'108.59.0.38',
      u'ID': u'CaioC57NM0BfA3WDRAG8LApascUxftg9U2rl4nU8OrqWfQfm_xO1A03EJR7XBYwGlx81IylQrK5DHhXsPt7MtQ=='
    },
    {
      u'EntryIP': u'108.59.0.39',
      u'Status': 1,
      u'Domain': u'us-va-103.protonvpn.com',
      u'ExitIP': u'108.59.0.39',
      u'ID': u'qh_qQPwjLZU-Uzx2oXLq5Bl3eS-gjhYm7mxO5rCBzGMa7oLhNMfshPmpP9QWj7d52NOT3X_UVLujhrnHigo3-w=='
    },
    {
      u'EntryIP': u'192.96.203.69',
      u'Status': 1,
      u'Domain': u'us-va-105.protonvpn.com',
      u'ExitIP': u'192.96.203.69',
      u'ID': u'8XiPu2ESH0R75Uy1GwwsyCozPE-s6Kj2bzI6Y6y6cvMvGNS_mg4jyn1ISvQCXL2meKCke1Uhek10wthQofxI1g=='
    },
    {
      u'EntryIP': u'192.96.203.70',
      u'Status': 1,
      u'Domain': u'us-va-106.protonvpn.com',
      u'ExitIP': u'192.96.203.70',
      u'ID': u'2fzIRNasmFQoJWJlGfdZsWn2Ml_5m5L6fNT6nSiOvKkPs12exOlDe04jbp2GSZRXFnj_iva7h8jEKe3d1MVAvQ=='
    },
    {
      u'EntryIP': u'207.244.109.179',
      u'Status': 1,
      u'Domain': u'us-va-109.protonvpn.com',
      u'ExitIP': u'207.244.109.179',
      u'ID': u'n8rT_cAdamsvX-hRp0NJC1QQAJ0guJWlQ3CIYw_MWCOmfewO_8cjyFG6YTTL-_Hl8nJjhdf39cSDXfXn9XcurA=='
    },
    {
      u'EntryIP': u'207.244.109.180',
      u'Status': 1,
      u'Domain': u'us-va-110.protonvpn.com',
      u'ExitIP': u'207.244.109.180',
      u'ID': u'lRE3UwLV1Do-w3DiOBbC5SW4vWOAli2YGqnraOLYbylmkM8RBpJVijqKjz5CWroZ2VozjSboH7uGXlgEymGEOg=='
    },
    {
      u'EntryIP': u'209.58.142.154',
      u'Status': 1,
      u'Domain': u'us-ca-101.protonvpn.com',
      u'ExitIP': u'209.58.142.154',
      u'ID': u'gze3wfvKprRzrcioqFxUqRsb-_LUQuigw0oMLznyk-Rz9SpNarGuYvC34Uuw9jwbqt_p4LfOKwhqnB2DsX3xOA=='
    },
    {
      u'EntryIP': u'209.58.142.155',
      u'Status': 1,
      u'Domain': u'us-ca-102.protonvpn.com',
      u'ExitIP': u'209.58.142.155',
      u'ID': u'BcMR48g9A40xFDikwlypz_0HUcAuDg4JLXaIXnU_3GTaHhMMpDAYmwLPSpslKww7jM980F3yTbkdDle-PQ1ZmQ=='
    },
    {
      u'EntryIP': u'209.58.142.157',
      u'Status': 1,
      u'Domain': u'us-ca-104.protonvpn.com',
      u'ExitIP': u'209.58.142.157',
      u'ID': u'Rc1jL2pgiCS80W-hQ9FXPDU24H3w17cSKsoMPzjzBDYeE_YeSbKUcDV7BzfUpUQibfRP0flcI8zcIkhltwDaYQ=='
    },
    {
      u'EntryIP': u'209.58.142.158',
      u'Status': 1,
      u'Domain': u'us-ca-105.protonvpn.com',
      u'ExitIP': u'209.58.142.158',
      u'ID': u'M0prDxG_M62NNnt_YYUmDifQTdLIsZED9sxRIXC4NscVDojDBDo1P04w-cRFYjkNFv35hV07jP9RzcOUTxE6Cw=='
    },
    {
      u'EntryIP': u'209.58.142.159',
      u'Status': 1,
      u'Domain': u'us-ca-106.protonvpn.com',
      u'ExitIP': u'209.58.142.159',
      u'ID': u'T3bFSHk4Sz7kkijmUnleDQpzWoZAPOaJY-ezFjkxdVB59YJdlUPgqeywUDpkzh5Cjaih3jYnSCLMmZ735mGTcA=='
    },
    {
      u'EntryIP': u'209.58.142.161',
      u'Status': 1,
      u'Domain': u'us-ca-108.protonvpn.com',
      u'ExitIP': u'209.58.142.161',
      u'ID': u'o5MB0znIKWC8H7dQ5UEqq8eIny-YTUiN7IF0nTdr1yv8j63rBtwtxv6UeY7kRRjA3i2JTg32V7rhvumdrOn7oQ=='
    },
    {
      u'EntryIP': u'209.58.147.210',
      u'Status': 1,
      u'Domain': u'us-tx-101.protonvpn.com',
      u'ExitIP': u'209.58.147.210',
      u'ID': u'4Q2Qxw3nW2DG1l1fk8SLIsDvYitpg4CcZI9WrF1pBAnNfYMyR7mQdJGGBkuig0vyZJsmJ-CIe8Z-7uK4e-g4XQ=='
    },
    {
      u'EntryIP': u'209.58.147.238',
      u'Status': 1,
      u'Domain': u'us-tx-102.protonvpn.com',
      u'ExitIP': u'209.58.147.238',
      u'ID': u'LV97svEYE6PZ4rjeT0FwZ5Iqni8UipJ38_mvPXs9Q3s9w4ItLaXh0L97jI3NBUe9VG5FxVjdG3atJ0pKTrftqw=='
    },
    {
      u'EntryIP': u'209.58.147.239',
      u'Status': 1,
      u'Domain': u'us-tx-103.protonvpn.com',
      u'ExitIP': u'209.58.147.239',
      u'ID': u'1KvjNslp9smK3cA0JXhCRAug-S7Dje_rg1lnRe2pCWI8HxwZ8tfp8Ii5qoqeDcBtpYltIsYYMsIvlvCk32Lytg=='
    },
    {
      u'EntryIP': u'209.58.147.241',
      u'Status': 1,
      u'Domain': u'us-tx-104.protonvpn.com',
      u'ExitIP': u'209.58.147.241',
      u'ID': u'2qf5zHWX_gSnFb8SHvLDBPIDhynjf3tvlv4-CBhXF6K-ZpROISfDmU8yDFdJ1gpKDMQgOpO0YneL04aOXEfLrg=='
    },
    {
      u'EntryIP': u'204.188.215.219',
      u'Status': 1,
      u'Domain': u'us-il-101.protonvpn.com',
      u'ExitIP': u'204.188.215.219',
      u'ID': u'kJ1HMEZ6D6mf08-mWOIHwqC6VtPySj4EMJ3X9-sV2DiX25JvTAX9PO0lwP2mMmiLVz5uVXACnmueOK8zrpD8Mw=='
    },
    {
      u'EntryIP': u'204.188.215.220',
      u'Status': 1,
      u'Domain': u'us-il-102.protonvpn.com',
      u'ExitIP': u'204.188.215.220',
      u'ID': u'jhRK9RMDowi2TaAIeOfK3xlOizL7ox_JrO-euMCD1h4HiNo87_wRsbPjvmUACGttSPfpnySVExjxIgKR7YMUjA=='
    },
    {
      u'EntryIP': u'204.188.215.221',
      u'Status': 1,
      u'Domain': u'us-il-103.protonvpn.com',
      u'ExitIP': u'204.188.215.221',
      u'ID': u'n6_cQciFQkEoTpy57hedhxZic_6GXA3MZgMRZAa8TMCW8m78md5y43YNhbCepjjyCibOxbXRwpW0tPaVgN4e1w=='
    },
    {
      u'EntryIP': u'209.58.147.242',
      u'Status': 1,
      u'Domain': u'us-tx-105.protonvpn.com',
      u'ExitIP': u'209.58.147.242',
      u'ID': u'Y18DHsGY0yYsV7Xcg_rQIKvqHL42jQNc_BNZULTSAAINUC8R8yVIiFkDSUz_kKwE6NAbRl0UKmXnI_NMLl6jTg=='
    },
    {
      u'EntryIP': u'209.58.147.244',
      u'Status': 1,
      u'Domain': u'us-tx-107.protonvpn.com',
      u'ExitIP': u'209.58.147.244',
      u'ID': u'l9MvEUIomf-av-zYM_uSqA01nCtWXAMOrx9OzLRSInY-NA7awCRmdDPC8jN4WHk1DVh6IR4weak57mk3RtwDzQ=='
    },
    {
      u'EntryIP': u'209.58.147.245',
      u'Status': 1,
      u'Domain': u'us-tx-108.protonvpn.com',
      u'ExitIP': u'209.58.147.245',
      u'ID': u'8KjC3mH70Qk8OKXmHVcJEeZieSonJo_rlem9H-ED5xk_4xaG6VIpAXPGDUvKpdQAg49TluACcccKV_kb3QykoQ=='
    }
  ],
  u'Score': 1.15551432,
  u'ExitCountry': u'US',
  u'Tier': 0,
  u'ID': u'GsNU4Fo0OcOwGTo54vgbXxzJWjgcqnVcONex1MwGAOA_uQN5gJOrYIIghHF16-lKxyiU4HJwW5nyOQ7MNUIIyQ==',
  u'EntryCountry': u'US',
  u'Name': u'US-FREE#1'
```

**Comment by xilopaint** [comment]
> The reason that it should not work that the first random.choice chooses a single element from the list. The second random.choice input is isn't a list, which triggers an exception.

Yes, it's a list. It's an output example of the first random.choice:

```
[{u'EntryIP': u'217.23.3.171', u'Status': 1, u'Domain': u'nl-104.protonvpn.com', u'ExitIP': u'217.23.3.171', u'ID': u'KV8mjImpquR4tux9teokTx9bRB3GDgJYgDV2r1PCaCVD9o8InZs99CZr_q2G0qyP8QES4FZyxdO5gU1K-2Jv7Q=='}, {u'EntryIP': u'89.39.107.205', u'Status': 1, u'Domain': u'nl-108.protonvpn.com', u'ExitIP': u'89.39.107.205', u'ID': u'pcCWuJFG38pl2T1bOFV1sZEwvFVZsbsDgoWx1SrDIWmxG_PtJyv-XvtTYK2vgcXRhOMNo8_D5k30Sh1KkWkjrg=='}, {u'EntryIP': u'89.39.107.201', u'Status': 1, u'Domain': u'nl-112.protonvpn.com', u'ExitIP': u'89.39.107.201', u'ID': u'SlU3wQzhOieDL18yX39n6IlsZTRHP66ealKLpP3wRiDItQuTfyGoC0_HVDqhuK_Khu9UdIKBHjyRMbWdbcwkjQ=='}, {u'EntryIP': u'89.39.107.197', u'Status': 1, u'Domain': u'nl-116.protonvpn.com', u'ExitIP': u'89.39.107.197', u'ID': u'ZrKSJOOOaz2mhYnzjxa8CDjbGIG0ijTbxuhpJ7_-E3EGE7weR9vePnc5_c0bPgKHNct0meIUTVPSQQ_OhyffCQ=='}, {u'EntryIP': u'89.39.107.193', u'Status': 1, u'Domain': u'nl-120.protonvpn.com', u'ExitIP': u'89.39.107.193', u'ID': u'3KczVDMHeUOC0l1SijmehL5Z1svVieFur_KcHbLqRIu5QwnoJV56FUcbrP0GjvLN5lGV3oDXP3zjyhax23tnmg=='}, {u'EntryIP': u'109.201.133.30', u'Status': 1, u'Domain': u'nl-128.protonvpn.com', u'ExitIP': u'109.201.133.30', u'ID': u'w0F4zk04gjMl8TcIfzMnHTKfG6meA8UK819CbagzD8xxbL53yR3pCcIUA2JZDAI6wnLRtzMrClbQJOdu8fUTSA=='}, {u'EntryIP': u'46.166.142.216', u'Status': 1, u'Domain': u'nl-131.protonvpn.com', u'ExitIP': u'46.166.142.216', u'ID': u'-IjWN9MBEdKAc048v0ebrhBfVhU3kjhdMoexQiTMXtQSkbW-9N59HuiVN6DFMqylIMkLTZoj34bMKxaxPnwfwQ=='}, {u'EntryIP': u'46.166.142.217', u'Status': 1, u'Domain': u'nl-132.protonvpn.com', u'ExitIP': u'46.166.142.217', u'ID': u'wUtKGRn-o2f6xEi9QY41pWkSe083gqB0S2M3oluhrYJniFunMulS6ohZj6BDHnt2motgpcS2AlROnSarrjXCVQ=='}, {u'EntryIP': u'46.166.142.221', u'Status': 1, u'Domain': u'nl-135.protonvpn.com', u'ExitIP': u'46.166.142.221', u'ID': u'tXDvpcaG8ntCuTK6pjl5rMSaQgdsdYe1qlgOduoO1yOWJwOTAnd064Sh1GJila__N2znK_sp43tnNGO_YngAew=='}, {u'EntryIP': u'46.166.142.222', u'Status': 1, u'Domain': u'nl-136.protonvpn.com', u'ExitIP': u'46.166.142.222', u'ID': u'7GerCBVsrXBIL8f_43e9QNsUpexhLAW3tIdHMxpu-hrba5tCsEnbC0TaLmvAcCXcEZbdwfezyvx3WM3iysICMw=='}]
```

**Comment by xilopaint** [comment]
This version should be easier to read:

```
candidate = random.choice(output)                       # Chosen candidate (type dict)
candidate_servers = candidate["Servers"]            # List of servers of the chosen candidate (type list)
server = random.choice(candidate_servers)         # Chosen server of the previous list (type dict)
server_id = server["ID"]                                           # Server id (type unicode)
```

Hope this clarify whatever doubt.

**Comment by xilopaint** [comment]
Hey @mazen160. The code works, but I think that I found something to discuss. Please, DM-me as soon as you can.

**Pull request closed without merging**
