### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by Rafficer**
Typo was reported by a fellow redditor here: https://www.reddit.com/r/ProtonVPN/comments/91ew2x/typo_in_error_message/

### CODE REVIEW

**Comment by mazen160** [comment]
Hi @Rafficer !!

Thanks for the PR. I have merged it. If there is no user-errors reported by tomorrow, we will start the versioning phase.
There are more to come soon!

Best,
Mazin

**Comment by mazen160** [comment]
Awesome ideas! I have noted it, and will try to figure out how to implement it with scalablity in mind.

The problem is this will require an HTTP request going everytime a user connects to a VPN (to check for update first).

An idea I got from your notes is to have a file with a timestamp of last update check. If it passes one week, we can show "would you like to check for updates?" or something similar.

The problem is CLI updating is not as suitable as in GUI; We can just issue an async request, and the user won't mind since it's a part of the app. But in the CLI, it would be either sync request which will be annoying, or an async request which won't be suitable since it will be unexpected.

I will have to look for a way to make the UX on this part better. Maybe it would be developed on next release

**Comment by mazen160** [comment]
- Next release we will start on KillSwitch implementation :fire:

**Comment by Rafficer** [comment]
Awesome, Killswitch is long awaited by a lot of people!

Yes, I thought about a timestamp as well and I think it's the best idea. Also, it should be possible to completely disable the automatic check for those that want to have the least amount of traffic as possible before connecting to the VPN.

**Pull request merged**
