### PR TITLE
Allow disabling openvpn daemonization via env variable

### PR DESCRIPTION
**Pull request by mafredri**
Hi 👋,

this PR adds support for disabling openvpn daemon mode. My use-case is running protonvpn-cli inside Docker and I thought it could be a nice addition. It does so by forking the connection detection to run in a child process so that we can execute `openvpn`. An alternative approach would've been to fork `openvpn` and wait for it down the line, I'm open to making that change if it's preferable.

At first I wanted to add this as a cli flag `--no-daemon`, but that would require rewriting the whole parsing of options and without major changes, would have to be the first option since all other options are *final*. Too big of a change for a random PR 😄.

(PS. I've fixed the indentation and made a few stylistic changes to the `wget` command, let me know if you want those removed to minimize the diff)

---

By setting `PROTONVPN_CLI_DAEMON=false` openvpn will not be daemonized
and the protonvpn-cli command will remain running for the duration of
the connection.

When daemon mode is disabled, the connection can be interrupted via
interrupt (Ctrl+C) or termination (kill -TERM) and the regular
disconnect code-path will be used.

Example of connecting to random server and hitting Ctrl+C after the
connection has been established:

```
$ PROTONVPN_CLI_DAEMON=false protonvpn-cli --random-connect
Fetching ProtonVPN servers...
[*] CLI logging mode enabled.
[*] Logs path: /root/.protonvpn-cli/connection_logs
Connecting...
[$] Connected!
[#] New IP: XXX.XXX.XXX.XXX
^CDisconnecting...
cp: can't create '/etc/resolv.conf': File exists
[#] Disconnected.
[#] Current IP: XXX.XXX.XXX.XXX
```

### CODE REVIEW

**Comment by mafredri** [comment]
While playing around with this some more, I realized that in a docker environment it would make more sense to replace the script with openvpn and remove the trap handling:

```
exec openvpn "${OPENVPN_OPTS[@]}"
```

There's really no reason to perform any form of disconnect/teardown. But that doesn't work for a regular user, so this PR is probably best as-is considering users, and could use some changes for Docker. Let me know what you think 😄.

**Comment by xilopaint** [comment]
> cp: can't create '/etc/resolv.conf': File exists

Why this error?

**Comment by mafredri** [comment]
> Why this error?

Not sure. I'm running `protonvpn-cli` in Alpine Linux with `openresolv`, maybe some minor behavioral difference between it and `resolvconf`? I fixed this locally at one point by changing `cp` to `cat >` but it might warrant more investigation.

**Comment by mafredri** [comment]
@xilopaint yeah, and also on line 322. The reason I said it might warrant more investigation is that it seems that there are actually two resolv.conf managers present. On the one hand, there's `modify_dns()`, but then there's also the `update-resolv-conf` script (which btw is required or proton-cli refuses to run) which uses `resolvconf` behind the scenes (e.g. from `openresolv`). Both are simultaneously trying to manage `resolv.conf` and that might lead to some bad times down the line 😅.

Didn't expand on this further, before, since it's not relevant for this PR. Might be worth it's own issue.

**Comment by mazen160** [comment]
Hi @mafredri

Thanks for the PR. I have to say, nice work!

I have reviewed the code, and it's working as expected. Also the trap part works correctly. 

Can you please fix the "PR conflict"? Once you do it, I will be merging the PR.

**Comment by mafredri** [comment]
@mazen160 done, I've rebased it against master :).

**Comment by mazen160** [comment]
Hi @mafredri !

I have merged the PR and fixed a bug that was discovered because of your PR in the openvpn_disconnect function :) 

I also did very minor changes, and tested the functionalities. Everything should be fine.

Please feel free to contribute more in the near future!! :) 

Best regards,
Mazin

**Comment by Tamaranch** [comment]
Hi @mazen160, @mafredri,
Unfortunately, I think we fall back in #114 by exiting with the exit status code of `wait` at line [555](https://github.com/ProtonVPN/protonvpn-cli/blob/ca1a45cbfe49377709660f12b1ec37a36ade96f5/protonvpn-cli.sh#L555)-[560](https://github.com/ProtonVPN/protonvpn-cli/blob/ca1a45cbfe49377709660f12b1ec37a36ade96f5/protonvpn-cli.sh#L560). The "`exit 1`" at line [536](https://github.com/ProtonVPN/protonvpn-cli/blob/ca1a45cbfe49377709660f12b1ec37a36ade96f5/protonvpn-cli.sh#L536) is no longer taken into account.

**Comment by mafredri** [comment]
Apologies, I had assumed `wait` will return the exit status of children even if no process is specified, this should now be fixed in #136 by explicitly waiting for the connection checker.

**Comment by mazen160** [comment]
@mafredri Awesome! It's now fixed!

**Pull request merged**
