### PR TITLE
Adding support for updating protonvpn-cli

### PR DESCRIPTION
**Pull request by arderyp**
This functionality hinges on all of the utility functionality residing in a single file (`protonvpn-cli.sh`), the name of that file not changing, and the `-install` option remaining and not being renamed.  Instead of adding a `git` dependency (which I personally think is actually fair to assume) we are instead grabbing the single raw script file from GitHub instead of cloning the repo and doing it that way.

### CODE REVIEW

**Comment by Rafficer** [comment]
What do you think about the idea of putting a version number somewhere and checking this every time the script runs and just notifying that an update is available (if the number is higher than the current version) and that the script can be updated with -update?

**Comment by xilopaint** [comment]
@Rafficer and where the number would be placed?

**Comment by arderyp** [comment]
You could have an option/argument to check if the installed version is current, which would grab the most recent script from github and compare some sort of hash (md5 or whatever) of the GH version and the local version.  But again, I still think replacing current with the same version or newer is safe and simplest.

**Comment by mazen160** [comment]
Hi @arderyp 

Thank you for the PR and the addition. I have been thinking about adding this part once I finish a number of todos.

The approach I have in mind currently is to download the script and get a hashsum of it, then comparing it with the current hashsum of the tool.
If there is an update, then it will be downloaded and placed on the place where the current code is placed.

Please let me know what you @all think about the approach.

We will keep this PR pending for 1-3 weeks max. Then I will do the modifications and merge it.

Thanks again!

**Comment by Rafficer** [comment]
The hashsum approach sounds good. Would you do it automatically or just notify and keep an -update flag?

**Comment by mazen160** [comment]
@Rafficer  
Using the -update flag, if there is an update, it will print that there is an update, then will download it and will show if the update went successfully.

**Comment by arderyp** [comment]
Sounds good @mazen160.  I think your approach is a good one.  I’ll just leave this be for now and let you take it from here.  Thanks again.

**Comment by mazen160** [comment]
@arderyp 
Awesome! 
Will do the functionality based on your initial approach.

Thanks again for the addition!

**Pull request closed without merging**
