### PR TITLE
Fix #58

### LINKED ISSUE #58: Uninstallation leaves current OpenVPN session running
When uninstalling the program while currently connected, it leaves the user without an option to disconnect the session after that (except manually finding and killing the process)

### PR DESCRIPTION
**Pull request by Rafficer**
Fix for #58 

Uninstallation function checks if a session is running currently and if so, disconnects that session before continuing with the uninstallation.

### CODE REVIEW

**Comment by mazen160** [comment]
Can you revert to this commit: 

https://github.com/ProtonVPN/protonvpn-cli/pull/59/commits/ccd9c311cf8807b2156f6bf13975aded8bf14f06

There is an unnecessary code reuse on the last commit.

I was going to write a patch exactly like the commit: https://github.com/ProtonVPN/protonvpn-cli/pull/59/commits/ccd9c311cf8807b2156f6bf13975aded8bf14f06

**Comment by Rafficer** [comment]
It isn't unneccessary. Most of the code is reused, yes.

Leaving it as it is on commit `ccd9c31` it will exit the script and doesn't continue with the uninstallation. I replaced exit with break in the loop.

**Comment by mazen160** [comment]
@Rafficer What do you think about this approach  ?  ;)

**Comment by Rafficer** [comment]
Didn't think about that. Looks a lot better :)

Thanks :)

**Comment by mazen160** [comment]
@Rafficer Awesome work as always! :+1:

**Pull request merged**
