### PR TITLE
Fix detect_platform_type value

### PR DESCRIPTION
**Pull request by xilopaint**

### CODE REVIEW

**Comment by xilopaint** [comment]
Hey @mazen160, in addition to these minor changes I'm thinking if it would worth to also change "Linux" and "MacOS" values to "linux" and "macos" (all lowercase letters). I don't see a reason to use different letter cases in the code. If you agree I can add a commit to this PR.

**Comment by mazen160** [comment]
Excellent addition! 

Maybe we can leave this PR open and you can push the update to this PR?

**Comment by xilopaint** [comment]
> Maybe we can leave this PR open and you can push the update to this PR?

Done.

**Comment by mazen160** [comment]
Perfect!! :100: :fire:

**Pull request merged**
