### PR TITLE
Make macOS checksums with shasum rather than sha512sum

### PR DESCRIPTION
**Pull request by xilopaint**
macOS has its own solution for checksums, so no need to install coreutils package with sha512sum.

### CODE REVIEW

**Comment by mazen160** [comment]
Hi @xilopaint 
Just letting you know that all macOS bugs and PRs will be added on batch. Including this PR.

I'm currently looking for a fix macOS DNS management part.

Thanks,
Mazin

**Comment by xilopaint** [comment]
@mazen160, no problem but this PR is not DNS related. It just adopts `shasum` rather than `sha512sum` for checksums in macOS, since it's stock in the platform.

protonvpn-cli code has been increasingly non-portable for macOS.

**Comment by xilopaint** [comment]
@mazen160, no problem but this PR is not DNS related. It just adopts shasum rather than sha512sum for checksums in macOS, since it's stock in the platform.

**Comment by mazen160** [comment]
Hi @xilopaint 
I have pushed an update now based on your code and input. 
https://github.com/ProtonVPN/protonvpn-cli/commit/ff077b182fbbb42569bec79ddcebec7b5c6f991a

The problem is, I have received an email ticket regarding FBSD support. Some changes on your PR needed to be done regarding shasum to work on FBSD too.

Thanks!!

Best,
Mazin

**Pull request closed without merging**
