### PR TITLE
Add single-line installation command

### PR DESCRIPTION
**Pull request by Rafficer**
For usabilities sake. Maybe there's a more beautiful version than calling those commands one after another. Didn't work for me with `wget -qO- ...` and ` | bash -s -- -install`

Also more beautiful would be to put those commands in an extra file, maybe even hosted on protonvpn.com and doing `wget -qO- https://protonvpn.com/support/linuxinstall | bash`

I just tested this. `wget -qO-  https://ncrypt.sh/linuxinstall_test | bash` looks a lot more beautiful and works the same.

I also thought about adding `echo "Initialize protonvpn-cli now with sudo protonvpn-cli -init"` at the end of the installation function, to make it more clear, but wanted to hear thoughts on that first :)

### CODE REVIEW

**Comment by mazen160** [comment]
HI @Rafficer 

Thanks for the PR!

I will discuss the approach with the team, I would prefer using `git` so it's more clear to users. 


Maybe we finish the next build, there is another installation method that are simpler.


We can use:

```bash
sudo bash -c "git clone https://github.com/ProtonVPN/protonvpn-cli.git ; ./protonvpn-cli/protonvpn-cli.sh -install"
```

In addition to the current one.

**Comment by Rafficer** [comment]
> We can use:
>`
sudo bash -c "git clone https://github.com/ProtonVPN/protonvpn-cli.git ; ./protonvpn-cli/protonvpn-cli.sh -install"
`
>In addition to the current one.

Sounds good to me :)

Maybe also consider to add `wget -qO- https://ncrypt.sh/linuxinstall_test | bash` (obviously on protonvpn.com) on the support page as alternative quick install.

**Comment by mazen160** [comment]
Definitely we will have a simpler installation method in the future.
We have on long-term at https://github.com/ProtonVPN/protonvpn-cli/issues/27

**Comment by mazen160** [comment]
Done ;)
Thank you again @Rafficer !

**Pull request closed without merging**
